# Generated by Django 3.1.4 on 2021-06-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.photographer')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
        ),
    ]
