# Generated by Django 3.1.4 on 2021-06-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruter')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
                ('talent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
            options={
                'unique_together': {('talent', 'ads')},
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='talents',
            field=models.ManyToManyField(through='ads.Application', to='accounts.Talent'),
        ),
    ]
