# Generated by Django 3.1.4 on 2021-06-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
