# Generated by Django 3.1.4 on 2021-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_photographer_is_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruter',
            name='company_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruter',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='profile_picture',
            field=models.ImageField(default='thumb_photos.png', upload_to='profile_picture'),
        ),
    ]
