# Generated by Django 3.1.4 on 2021-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210617_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruter',
            name='originated_country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
