# Generated by Django 3.1.4 on 2021-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recruter_originated_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='talents',
            field=models.ManyToManyField(to='accounts.Talent'),
        ),
    ]
