# Generated by Django 3.1.4 on 2021-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210617_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='talents',
        ),
        migrations.AddField(
            model_name='talent',
            name='category',
            field=models.ManyToManyField(to='accounts.Category'),
        ),
    ]
